
title: Cafeteria Tematica
email: wninasaume@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Cafeteria temática es un lugar donde encontrarás un ambiente calido
  donde podrás disfrutar de los platos de la época de los 50.
baseurl: "/myNewSite" # the subpath of your site, e.g. /blog
url: "https://wilmernb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed


